### ISSUE TITLE
No new release in 2.5 years.

### ISSUE THREAD

**Issue by mikedarcy** [LibraryOfCongress/bagit-python#148]
Are there any plans to release an update to this software? As Python3 (especially 3.8, 3.9) becomes more prevalent, I see lots of this nuisance warning whenever `bagit.py` is loaded (which can happen a lot, indirectly, if one's code has it as a dependency):

```
/usr/local/bin/bagit.py:629: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if not manifest_filename.find("tagmanifest-") is -1:
```
This was addressed in 6e14a50. The commits going back to mid-June 2018 don't seem like they touch major functionality in any significant way but are rather more like quality of life fixes and general upkeep. Any reason they can't be rolled out into a minor point release?

**Comment by acdha** [comment]
Sorry about that. Coincidentally, that's about the same period of time that I've been working on other projects 😀 

https://pypi.org/project/bagit/1.8.0/ is out now

**Comment by mikedarcy** [comment]
Thanks for the quick response Chris!
