### ISSUE TITLE
latest releases not on the primary branch?

### ISSUE THREAD

**Issue by mr-c** [LibraryOfCongress/bagit-python#150]
https://github.com/LibraryOfCongress/bagit-python/releases/tag/v1.8.1 which is https://github.com/LibraryOfCongress/bagit-python/commit/e15964e6fdff3588b92889d4ae73a190a34caab9

> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

**Comment by acdha** [comment]
Ah, looks like I made a mistake and tagged the working branch rather than the merge result (the contents were identical but not the branch history). I just corrected the v1.8.1 tag.
