### ISSUE TITLE
v1.5.4?

### ISSUE THREAD

**Issue by edsu** [LibraryOfCongress/bagit-python#45]
I see that v1.5.3 never made it to PyPI and was thinking perhaps now would be a good time to coordinate a Github and PyPI release for v1.5.4? Also, would anyone at LoC like to have permission to upload to PyPI for bagit-python?

**Comment by dbrunton** [comment]
Makes sense to me. I just drafted a release: tag: v1.5.4, name: Version 1.5.4. "Improved PEP-8 conformance, change logging to use logger, file opening to use with, cleaned up some error handling, and removed of sys.exit."

I made a draft, but it doesn't appear to be readable except for by me.

**Comment by dbrunton** [comment]
@acdha volunteered to jump in on PyPI. Other than incrementing the version in setup.py, is there other bookkeeping that needs to happen on GitHub? (There's a v1.5.4 branch with that small change).

**Comment by edsu** [comment]
It looks like @acdha has the keys to PyPI already (must've done that a while ago). So he should be all set to do a release.

**Comment by dbrunton** [comment]
@acdha fire at will: https://github.com/LibraryOfCongress/bagit-python/releases/tag/v1.5.4

@edsu thank you!

**Comment by acdha** [comment]
Just uploaded:

https://pypi.python.org/pypi/bagit/1.5.4

**Comment by acdha** [comment]
(someone with access can close this issue)

**Comment by edsu** [comment]
Weird, you don't have GitHub access for this repo?

**Comment by acdha** [comment]
@edsu apparently only enough to bother people in the comments

**Comment by dbrunton** [comment]
oops :) try it now?

**Comment by edsu** [comment]
Have you have ever had one of those moments where you wanted to "like" someone's comment on GitHub?

**Comment by edsu** [comment]
Is it just me, or does it look like the build failed?

**Comment by dbrunton** [comment]
Boy, it sure did: "The command "git checkout -qf 5ad5f6ed0573347f27c0ab23a2d81bea92fa9ca1" failed and exited with 128 during ."

**Comment by dbrunton** [comment]
Looks like I messed up the tag on the build.

**Comment by acdha** [comment]
It looks like there was both a tag and a branch with the name v1.5.4. I just deleted the now-moot branch.

**Comment by acdha** [comment]
Ah, there we go:

https://travis-ci.org/LibraryOfCongress/bagit-python/builds/70209387

https://libraryofcongress.github.io/bagit-python/ sure looks nice now
