### ISSUE TITLE
Bench.py ftplib error_perm 550

### ISSUE THREAD

**Issue by kieranjol** [LibraryOfCongress/bagit-python#65]
I'm using Ubuntu 14.04, and the bench.py script seems to fail at the NASA download phase:

```
:~/bagit-python$ ./bench.py 
fetching some images to bag up from nasa
Traceback (most recent call last):
  File "./bench.py", line 24, in <module>
    ftp.cwd('/photo_gallery/hi-res/planetary/mars/')
  File "/usr/lib/python2.7/ftplib.py", line 562, in cwd
    return self.voidcmd(cmd)
  File "/usr/lib/python2.7/ftplib.py", line 254, in voidcmd
    return self.voidresp()
  File "/usr/lib/python2.7/ftplib.py", line 229, in voidresp
    resp = self.getresp()
  File "/usr/lib/python2.7/ftplib.py", line 224, in getresp
    raise error_perm, resp
ftplib.error_perm: 550 /photo_gallery/hi-res/planetary/mars/: No such file or directory
```

**Comment by johnscancella** [comment]
Looks like the ftp server `nssdcftp.gsfc.nasa.gov` no longer contains a path `/photo_gallery/hi-res/planetary/mars/` or even `/photo_gallery` for that matter. @acdha suggestions on where to get the same data from NASA?

**Comment by kieranjol** [comment]
Looks like it's been moved into the /pub/misc/  directory. Pull request sent : https://github.com/LibraryOfCongress/bagit-python/pull/66
Works on OSX anyhow.
