### ISSUE TITLE
Multiple entries of a file in a manifest should not be allowed

### ISSUE THREAD

**Issue by nkrabben** [LibraryOfCongress/bagit-python#94]
If a hash manifest has multiple entries for a file, bagit.py silently overwrites these hashes on top of one another.
https://github.com/LibraryOfCongress/bagit-python/blob/master/bagit.py#L593

This isn't explicitly against the BagIt spec (2.1.3 is the relevant section), but I think bagit.py should flag these situations as invalid when loading a manifest.

**Comment by acdha** [comment]
I updated our proposed 1.0 spec changes to include that: 66c24ebd46cf28c4543e0741ae56502cae141020

**Comment by acdha** [comment]
Shipped in 1.6.0
